# Generated by Django 3.2.25 on 2025-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20250206_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Progress', 'Progress')], default='Pending', max_length=20),
        ),
    ]
